name: Node.js CI

on: [push]

jobs:
  build:
    permissions:
      contents: read
      pull-requests: write  

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - run: npm run build --if-present
    - run: npm test

