name: Terraform Full CI Checks

on:
  push:
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

permissions:
  contents: read
  security-events: write

jobs:
  terraform-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/

      - name: Install TFLint
        run: |
          set -e
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: Run TFLint
        run: tflint --recursive
        working-directory: terraform/

      - name: Install tfsec
        run: |
          set -e
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash

      - name: Run tfsec and generate reports
        id: tfsec
        run: |
          mkdir -p tfsec-report
          tfsec terraform/ --format sarif --out tfsec-report/tfsec.sarif --format json --out tfsec-report/tfsec.json || echo "tfsec finished with issues"
      
          # Print summary in logs
          issues_count=$(jq '.results | length' tfsec-report/tfsec.json)
          echo "tfsec found $issues_count issue(s)."
          if [ "$issues_count" -gt 0 ]; then
            echo "Detailed issues:"
            jq -r '.results[] | "- [\(.rule_id)](\(.links[0])): \(.description) (Severity: \(.severity))"' tfsec-report/tfsec.json
          fi
      
      - name: Fail if tfsec found issues
        run: |
          count=$(jq '.results | length' tfsec-report/tfsec.json)
          if [ "$count" -gt 0 ]; then
            echo "Failing pipeline due to tfsec issues."
            exit 1
          fi
      
      - name: Upload tfsec SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: tfsec-report/tfsec.sarif


      - name: Setup Python (Checkov)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: |
          set -e
          pip install checkov

      - name: Run Checkov
        run: checkov -d terraform/ --output sarif --output-file-path checkov.sarif

      - name: Upload Checkov SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: success()  # Only run if checkov succeeded
        with:
          sarif_file: checkov.sarif
