name: DAST ZAP

on: [push]
jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build and run the app on port 3000
      - name: Start App Container
        run: |
          docker build -t my-app .
          docker run -d -p 3000:3000 --name my-app-container my-app  # Map host:container port
          sleep 10  # Wait for app to start

      # Scan http://localhost:5000 (not 8080)
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.6.0
        with:
          target: 'http://localhost:3000'  # Updated port
          fail_action: true
          report_html: 'zap-report.html'  # Explicitly name the report file
          report_md: 'zap-report.md'  
  
      - name: Upload ZAP Report
        if: always()  # Upload even if the scan fails
        uses: actions/upload-artifact@v3
        with:
          name: zap-scan-report  # ✅ Valid name (lowercase + hyphen)
          path: |
            zap-report.html
            zap-report.md

      # Cleanup
      - name: Stop App Container
        if: always()
        run: |
          docker stop my-app-container
          docker rm my-app-container
