name: DAST ZAP

on: 
  push:
      paths-ignore:
      - '.github/workflows/ci-cd.yml'
      - '.github/workflows/zap.yml'
jobs:
  dast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build and run the app on port 3000
      - name: Start App Container
        run: |
          docker build -t my-app .
          docker run -d -p 3000:3000 --name my-app-container my-app  # Map host:container port
          sleep 10  # Wait for app to start

      # Scan http://localhost:5000 (not 8080)
      - name: OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'http://localhost:3000'  # Updated port

      - name: List All Artifacts (Debug)
        run: |
          echo "Existing artifacts:"
          ls -la ${{ github.workspace }}/*.html ${{ github.workspace }}/*.json || echo "No artifacts found"

      # Cleanup
      - name: Stop App Container
        if: always()
        run: |
          docker stop my-app-container
          docker rm my-app-container
